version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - product-service
      - cart-service
      - order-service
    environment:
      FRONTEND_PORT: 5000
      PRODUCT_API_URL: http://product-service:5001
      CART_API_URL: http://cart-service:5002
      ORDER_API_URL: http://order-service:5003
    command: ["npm", "run", "start:frontend"]
    restart: unless-stopped

  product-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      PRODUCT_PORT: 5001
      DB_SCHEMA_NAME: ${DB_SCHEMA_NAME}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_HOST_URL: ${DB_HOST_URL}
      DB_PORT: ${DB_PORT}
    command: ["npm", "run", "start:product"]
    restart: unless-stopped

  cart-service:
    build: .
    ports:
      - "5002:5002"
    environment:
      CART_PORT: 5002
      DB_SCHEMA_NAME: ${DB_SCHEMA_NAME}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_HOST_URL: ${DB_HOST_URL}
      DB_PORT: ${DB_PORT}
    command: ["npm", "run", "start:cart"]
    restart: unless-stopped

  order-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      ORDER_PORT: 5003
      DB_SCHEMA_NAME: ${DB_SCHEMA_NAME}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_HOST_URL: ${DB_HOST_URL}
      DB_PORT: ${DB_PORT}
    command: ["npm", "run", "start:order"]
    restart: unless-stopped