kind: Deployment 
apiVersion: apps/v1
metadata:
  name: backend-product-deployment
  namespace: ecommerce
  labels:
    app: backend-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-product
  template:
    metadata:
      labels:
        app: backend-product
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: ecommerce-backend-product
          image: 727646469309.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-product:8e7e29ea340912508369e829390d37fe61566f73
          command: ["npm", "run", "start:product"]
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:  
                name: dev-eks-argocd-secret
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"