kind: Deployment 
apiVersion: apps/v1
metadata:
  name: backend-cart-deployment
  labels:
    app: backend-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-cart
  template:
    metadata:
      labels:
        app: backend-cart
    spec:
      imagePullSecrets:
              - name: ecr-secret        
      containers:
        - name: ecommerce-backend-cart
          image: <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/ecommerce-cart:latest
          command: ["npm", "run", "start:cart"]
          ports:
            - containerPort: 5002
          envFrom:
            - secretRef:
                name: ecommerce-secret
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
