apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
stringData:
  DB_SCHEMA_NAME: ecommerce # ZWNvbW1lcmNl #
  DB_USER_NAME: admin #YWRtaW4= #
  DB_USER_PASSWORD: 3GV3zMIDdauCHgttGWDe #M0dWM3pNSURkYXVDSGd0dEdXRGU= #created bash64 encoded value
  DB_HOST_URL: k8s-db.c5qs4y22mlwm.us-east-1.rds.amazonaws.com #azhzLWRiLmM1cXM0eTIybWx3bS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20= #
  DB_PORT: "3306" #"MzMwNg=="