apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-eks-argocd-secret
  namespace: ecommerce
spec:
  refreshInterval: "1h"
  
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: dev-eks-argocd-secret
  data:
  - secretKey: DB_USER_NAME
    remoteRef:
      key: dev-eks-argocd-secret
      property: DB_USER_NAME
  - secretKey: DB_SCHEMA_NAME
    remoteRef:
      key: dev-eks-argocd-secret
      property: DB_SCHEMA_NAME
  - secretKey: DB_USER_PASSWORD
    remoteRef:
      key: dev-eks-argocd-secret
      property: DB_USER_PASSWORD
  - secretKey: DB_HOST_URL
    remoteRef:
      key: dev-eks-argocd-secret
      property: DB_HOST_URL
  - secretKey: DB_PORT
    remoteRef:
      key: dev-eks-argocd-secret
      property: DB_PORT
  - secretKey: JWT_SECRET
    remoteRef:
      key: dev-eks-argocd-secret
      property: JWT_SECRET