apiVersion: v1  
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    eks.amazon.com/role-arn: arn:aws:iam::727646469309:role/eks-argocd-external-secrets-role

