cluster:
  name: ecommerce-cluster

collector:
  prometheus:
    enabled: true

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          selector:
            matchLabels:
              type: prometheus
          resources:
            requests:
              storage: 5Gi

grafana:
  persistence:
    enabled: true
    storageClassName: manual
    selector:
      matchLabels:
        type: grafana
    accessModes:
      - ReadWriteOnce
    size: 2Gi