name: Build & Push Images

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build & Push Images
        run: |
          docker build -t $ECR_REGISTRY/ecommerce-cart:latest .
          docker push $ECR_REGISTRY/ecommerce-cart:latest

          docker build -t $ECR_REGISTRY/ecommerce-order:latest .
          docker push $ECR_REGISTRY/ecommerce-order:latest

          docker build -t $ECR_REGISTRY/ecommerce-product:latest .
          docker push $ECR_REGISTRY/ecommerce-product:latest

          docker build -t $ECR_REGISTRY/ecommerce-frontend:latest .
          docker push $ECR_REGISTRY/ecommerce-frontend:latest